apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
  namespace: default
  labels:
    app: shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: venky3036/food:eccom
        imagePullPolicy: Always
        ports:
        - containerPort: 80
